repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.290"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    - id: nbqa-ruff
      additional_dependencies: [ruff==0.0.290]
      args: ["--extend-ignore=F821,F401,F841,F811,E501"]
